# Generated by Django 4.1.13 on 2024-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='purpose',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
